apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.0.156:8001/nginx
       # lifecycle:
       #   postStart:
       #     exec:
       #       #command: ["/bin/sh", "-c", "t=/usr/local/activenginx/data; d=/mnt/`date +%Y-%m-%d-%H-%M-%S`-`hostname`; mkdir -p $d; rm -rf $t; ln -s $d $t "]
       #       command: ["/bin/sh", "-c", "t=/usr/local/activenginx/data; d=/mnt/`hostname`; mkdir -p $d; rm -rf $t; ln -s $d $t "]
       # resources:
       #   requests:
       #     cpu: "1"
       #     memory: "500Mi"
       #   limits:
       #     cpu: "1"
       #     memory: "500Mi"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey
