#
#create username,ex    echo -n "admin" | base64
#create username,password    echo -n "1f2d1e2e67df" | base64
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
type: Opaque
data:
  username: eXk=
  password: MTIzNDU2
