FROM 192.168.0.45:5000/base
MAINTAINER lstar 442132099@qq.com
ADD sources.list /etc/apt/sources.list
RUN apt-get update && apt-get install -y openjdk-8-jdk --allow-unauthenticated
RUN apt-get install -y kibana --allow-unauthenticated
ADD kibana.yml  /etc/kibana/kibana.yml
###添加时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 5601
##VOLUME [/data]
ADD run.sh .
ENTRYPOINT [ "/run.sh"]
