apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: 172.16.74.150:5000/kafka
        ports:
        - containerPort: 9092
        env:
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2
        - name: ZOOKEEPER_SERVER_3
          value: zoo3
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: [AWS_LB_DNS_or_YOUR_DNS_POINTING_AT_IT]
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: zoo1:2181,zoo2:2181,zoo3:2181
#        - name: KAFKA_CREATE_TOPICS
#          value: mytopic:2:1
