FROM 172.16.74.150:5000/base
MAINTAINER lstar 442132099@qq.com
ADD zookeeper-3.4.10.tar.gz .
ADD start.sh /usr/bin/start.sh
#RUN mv zookeeper-3.4.10 /usr/local/zookeeper && groupadd -g 201 zookeeper && useradd -u 200 -g zookeeper zookeeper && mkdir /var/lib/zookeeper && chmod +x /usr/local/sbin/start.sh
RUN mv zookeeper-3.4.10 /usr/local/zookeeper && mkdir /var/lib/zookeeper && chmod +x /usr/bin/start.sh
ADD zoo.cfg /usr/local/zookeeper/conf/zoo.cfg 
##添加时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 2181 2888 3888
#VOLUME [/etc/redis]
#ADD cluster.sh /usr/bin/cluster.sh
#ENTRYPOINT ["/bin/bash -c","/usr/bin/start.sh"]
ENTRYPOINT ["/usr/bin/start.sh"]
#ENTRYPOINT ["/usr/bin/supervisord"]
