FROM 192.168.0.45:5000/base
MAINTAINER lstar 442132099@qq.com
ADD sources.list /etc/apt/sources.list
RUN apt-get update && apt-get install -y openjdk-8-jdk --allow-unauthenticated
RUN apt-get install -y logstash --allow-unauthenticated
ADD logstash.conf /etc/logstash/conf.d/logstash.conf 
ADD logstash.yml  /etc/logstash/logstash.yml
RUN cp -r /etc/logstash /usr/share/logstash/config
###添加时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
EXPOSE 9600
##VOLUME [/data]
ADD run.sh .
ENTRYPOINT [ "/run.sh"]
